Better specify repository name constraints
dead-claudia/github-limits pull request #4
Opened 2021-11-29 07:16 UTC by xmo-odoo

* swap "character" for "codepoint" for better precision as that seems like what github works with
* adds the underscore (`_`) which was missing from the list of valids
* clarify that "alphanumeric" is ascii-only not e.g. unicode categories
* specifies that github automatically replaces *sequences* of invalid codepoints by a single hyphen (so `'a'` followed by 150 emoji followed by `'z'` is the valid repository name `a-z`)
* left implied: github does not perform any normalisation (or denormalisation) before sanitisation

Closes #3

2021-11-29 19:38 UTC, isiahmeadows requested changes

2021-11-29 19:38 UTC, isiahmeadows commented on README.md
> +- Max length: 100 codepoints
Could you split this into two words? Unicode uses two words for it, and I'd like to stay consistent with their usage.
```suggestion
- Max length: 100 code points
```

2021-11-29 19:38 UTC, isiahmeadows commented on README.md
> +- All codepoints must be either a hyphen (`-`), an underscore (`_`), a period (`.`), or ASCII alphanumeric
See above + a minor grammatical nit.

```suggestion
- All code points must be either a hyphen (`-`), an underscore (`_`), a period (`.`), or an ASCII alphanumeric
```

2021-11-29 19:38 UTC, isiahmeadows commented on README.md
> +Note: sequences of invalid codepoints are automatically replaced by a single hyphen (`-`)
See above
```suggestion
Note: sequences of invalid code points are automatically replaced by a single hyphen (`-`)  
```

2021-11-30 06:55 UTC, xmo-odoo commented
PR updated to substitute "codepoints" for "code points". Do you now if GFM supports footnotes? Since the goal is to clarify the wording I figure it might be useful to link to the official glossary definition.

Also is there a todo somewhere for things which would be nice for somebody with the inclination to check? While browsing the glossary, I figured it might be interesting to see whether it's really [code points](https://unicode.org/glossary/#code_point) or actually [USVs](https://unicode.org/glossary/#unicode_scalar_value) (code-points excluding for surrogates). I figure it's probably USVs but my test harness can't generate invalid utf8.

2021-11-30 06:56 UTC, isiahmeadows approved these changes

2021-11-30 07:01 UTC, isiahmeadows commented
@xmo-odoo 

> Do you now if GFM supports footnotes?

Unfortunately, it does not. You can kind of emulate them with `<sup>` elements (`<sup>[1]</sup>` &rarr; <sup>[1]</sup>) with inner links or whatnot, but it doesn't have any *native* support like MediaWiki's `<ref>` and `<cite>` elements.

> Also is there a todo somewhere for things which would be nice for somebody with the inclination to check? While browsing the glossary, I figured it might be interesting to see whether it's really [code points](https://unicode.org/glossary/#code_point) or actually [USVs](https://unicode.org/glossary/#unicode_scalar_value) (code-points excluding for surrogates). I figure it's probably USVs but my test harness can't generate invalid utf8.

There isn't. Just file an issue and I can leave it open for someone to maybe take on in the future. (This repo isn't even remotely a priority thing for me.)

2021-11-30 07:08 UTC, xmo-odoo commented
> > Also is there a todo somewhere for things which would be nice for somebody with the inclination to check? While browsing the glossary, I figured it might be interesting to see whether it's really [code points](https://unicode.org/glossary/#code_point) or actually [USVs](https://unicode.org/glossary/#unicode_scalar_value) (code-points excluding for surrogates). I figure it's probably USVs but my test harness can't generate invalid utf8.
> 
> There isn't. Just file an issue and I can leave it open for someone to maybe take on in the future. (This repo isn't even remotely a priority thing for me.)

Fair enough. Still, a useful resource, thank your for having put it out.

2021-12-03 07:06 UTC, xmo-odoo commented
@isiahmeadows is there anything more I need to change?

2021-12-03 08:08 UTC, merged

2021-12-03 08:08 UTC, isiahmeadows commented
Nope, just a little late with the merge. 🙂

2021-12-03 09:51 UTC, xmo-odoo commented
> Nope, just a little late with the merge. slightly_smiling_face

Cool, thanks, I was worried I'd missed something.